project:
  type: book
  output-dir: docs

jupyter: python3

book:
  title: "Convex Optimization"
  author: "Siyu Chen"
  date: "2024/3/7"
  chapters:
    - index.qmd
    - part: "Term Project"
      chapters:
        - proposal.qmd
        - Project.qmd
        - project_code.ipynb
    - part: "Homework"
      chapters:
        - GradientMethod.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

